import { Inter } from "next/font/google"
import Head from "next/head"
import Image from "next/image"
import { Button } from "antd"
import Link from "next/link"

const inter = Inter({ subsets: ["latin"] })

export async function getServerSideProps() {
  let signs = [
    "Capricorn",
    "Aquarius",
    "Pisces",
    "Aries",
    "Taurus",
    "Gemini",
    "Cancer",
    "Leo",
    "Virgo",
    "Libra",
    "Scorpio",
    "Sagittarius",
  ]

  return {
    props: {
      signs,
    },
  }
}

export default function Home(props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {props.signs.map((sign) => (
          <Link key={sign} href={`/${sign.toLowerCase()}`}>
            <Button key={sign} style={{ marginBottom: "5px" }} block>
              {sign}
            </Button>
          </Link>
        ))}
      </main>
    </>
  )
}
